[GLOBAL]
pants_version = "2.14.0"
pantsd = true 

backend_packages = [
    "pants.backend.python"
]

[source]
marker_filenames = ["BUILD"]

[python]
interpreter_constraints = [">=3.9"]

[anonymous-telemetry]
enabled = false
